### ISSUE TITLE
the /api path for the swagger specs is different from the node reply

### ISSUE THREAD

**Issue by noandrea** [aeternity/aesophia_http#15]
Hello,
the node reply for the swagger specs from the compiler returns a root object 
```
{
   "api": {
      "swagger": "2.0",
      ...
   }
} 
```
while for the node `/api` the root object is directly 
```
{
    "swagger": "2.0",
    ...
} 
```

is it possible to change the compiler http behaviour to be consistent with the one used in the node?

**Comment by hanssv** [comment]
Yes, it is open source, pull requests are welcome.

**Comment by hanssv** [comment]
#17

**Comment by hanssv** [comment]
Merged
