### ISSUE TITLE
Encoding call data with address type args

### ISSUE THREAD

**Issue by nduchak** [aeternity/aesophia_http#16]
Hey, i have a strange behavior when try to encode call-data for this contract:
```
contract Identity =
  type state = ()
  function main(x : address) : address = x
```
This is the `encode-call` body: `{ source: 'SOURCE', function: 'main', arguments:['0x485edabd5526cea1a4bfb164b3de1c6ea67241723391efa1c9a287a1f34c1145' ] }`
And the response is: 
```
Type errors
Cannot unify address        
and int
when checking the application at line 5, column 23 of  main : (address) => address to arguments 
0x485EDABD5526CEA1A4BFB164B3DE1C6EA67241723391EFA1C9A287A1F34C1145 :  int
```

**Comment by hanssv** [comment]
Address literals are written `"#3425ac23..."`

**Comment by nduchak** [comment]
Cool! Thank you 👍
