### ISSUE TITLE
Decode data: `sophia-type` format

### ISSUE THREAD

**Issue by nduchak** [aeternity/aesophia_http#28]
Can we change `sophia-type` prop of `/decode-data` API endpoint
to take `JSON` return type from ACI object(`{ list: ['int'] }`) instead of string (`'list(int)'`)???

**Comment by nikita-fuchs** [comment]
@rvirding naz knows what the aci is to be used for ;) ! can we have this API take ACI format input?

**Comment by rvirding** [comment]
I will check it.

**Comment by hanssv** [comment]
Check the new `/decode-call-result` endpoint, it uses a (stub-)contract and function name as input, so no need to input the type explicitly. #33
