### ISSUE TITLE
[Request] Add the option to decode return data using bytecode (same as implemented for calldata)

### ISSUE THREAD

**Issue by shekhar-shubhendu** [aeternity/aesophia_http#41]
#### Endpoint
`/decode-call-result/bytecode`

#### Usage
decode call result value using just the contract bytecode without the need for contract source.

**Comment by shekhar-shubhendu** [comment]
it seems to be already present here https://github.com/aeternity/aesophia_http/blob/extend-aci-interface/apps/aesophia_http/src/aesophia_http_handler.erl#L265

**Comment by hanssv** [comment]
That is just for AEVM

**Comment by shekhar-shubhendu** [comment]
> That is just for AEVM

ok. but can we still have this endpoint?

**Comment by hanssv** [comment]
Implemented in #46
