### ISSUE TITLE
400 response for higher order functions

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aesophia_http#65]
Hey, when doing 

```
entrypoint a_function(test : (int) => int ) : (int) => int  =
        test 
```

I'm getting `400` from `https://latest.compiler.aepps.com/aci` instead of a proper response / error message, whereas the compiler itself properly complains.

**Comment by radrow** [comment]
Does that reproduce on updated local service?

**Comment by hanssv** [comment]
It does not reproduce...
```
$ make docker
Using default tag: latest
latest: Pulling from aeternity/builder
4007a89234b4: Pull complete 
5dfa26c6b9c9: Pull complete 
...

$ docker run -p 3080:3080 -it aeternity/aesophia_http:local
...
```

And then in a different shell:
```
$ CONTRACT="contract C = entrypoint a_function(test : (int) => int ) : (int) => int = test"
$ curl -H "Content-Type: application/json" -d "{\"code\":\"$CONTRACT\",\"options\":{\"backend\":\"fate\"}}" -X POST http://localhost:3080/compile
[{"message":"The argument\n  test : (int) => int\nof entrypoint 'a_function' has a higher-order (contains function types) type.\n","pos":{"col":25,"line":2},"type":"code_error"}]
```

So works exactly as it should as far as I can tell?

**Comment by radrow** [comment]
Maybe the http interface is outdated?

**Comment by nikita-fuchs** [comment]
@hanssv `/compile` is not the culprit here, `/aci` is what's struggling

**Comment by hanssv** [comment]
The `/aci` endpoint won't compile the (stub-)contract so of course it will not report an error?

**Comment by hanssv** [comment]
Neither will the compiler BTW:
```
$ ./aesophia_cli --create_json_aci /tmp/bar.aes 
[{"contract":{"functions":[{"arguments":[{"name":"test","type":{"function":{"arguments":["int"],"returns":"int"}}}],"name":"a_function","payable":false,"returns":{"function":{"arguments":["int"],"returns":"int"}},"stateful":false}],"name":"C","payable":false,"type_defs":[]}}]
```

**Comment by nikita-fuchs** [comment]
I took a look again, getting a `200`now. The errors I'm fetching for aestudio come from `https://latest.compiler.aepps.com/aci` , and it returns `error`s, like 

`[{"message":"Unexpected identifier x.\n","pos":{"col":12,"line":12},"type":"parse_error"}]`


Right now, for a contract containing a higher order function, it just returns me a "semi-correct" ACI although the higher order function is not allowed when compiling.

E.g.

```
    entrypoint a_function(test : (int) => int ) : (int) => int  =
        test 
````
gives an ACI:
```
"name":"a_function",
               "payable":false,
               "returns":{
                  "function":{
                     "arguments":[
                        "int"
                     ],
                     "returns":"int"
                  }
               },
               "stateful":false
               ```
Although it should be throwing an error.

**Comment by hanssv** [comment]
There is a difference between a parse error and a code error.

It was super duper important that ACI generation was fast... Go figure.

**Comment by nikita-fuchs** [comment]
Can't recall importance for fast ACI generation as it's only really needed for _after_ deployment as you correctly pointed out. Currently, the `/compile` endpoint is called only upon contract deployment.  Assuming that endpoint returns a bigger set of error messages formatted the same way as the aestudio is now used to from the /aci endpoint, we could just change ae studio to speak to `/compile` for dev-time error reporting in the side bar and that's it ?

**Comment by hanssv** [comment]
Hehe, people tend to forget their imagined important requirements :-)

Yes, `/compile` will provide a (much) bigger set of errors, and according to the spec they should be formatted in the same way.

**Comment by nikita-fuchs** [comment]
🤷‍♂️

will try `/compile` then.
