### ISSUE TITLE
Don't duplicate line and col in error messages

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aesophia_http#79]
In case of error, `/compile` endpoint responses:
```json
[{
  "message":"Unbound variable baz at line 3, column 32\\n",
  "pos":{ "col":32, "line":3 },
  "type":"type_error"
}, {
  "message":"Unbound variable baz at line 4, column 33\\n",
  "pos":{ "col":33, "line":4 },
  "type":"type_error"
}]
```
The numbers of line and column are duplicated in the message and in separate fields. Looks reasonable to remove them from the message for better customization of how to present them to the user. For example, I would like to show just "type_error:33:4: Unbound variable baz".

**Comment by hanssv** [comment]
This has nothing to do with the HTTP-compiler that is how errors are reported from `aesophia`.
