### ISSUE TITLE
Remove trailing newline at the end of error messages

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aesophia_http#80]
In case of error, `/compile` endpoint responses:

```json
[{
  "message":"Unbound variable baz at line 3, column 32\\n",
  "pos":{ "col":32, "line":3 },
  "type":"type_error"
}, {
  "message":"Unbound variable baz at line 4, column 33\\n",
  "pos":{ "col":33, "line":4 },
  "type":"type_error"
}]
```

Trailing newline chars look extra, brings to broken output while doing something obvious like `response.body.map(({ message })).join('; ')`

**Comment by hanssv** [comment]
The HTTP-compiler does not have its own error message formatting, this should go towards `aesophia`.

**Comment by davidyuk** [comment]
The upstream issue is resolved, but seems that the original issue is not fixed here yet.
